version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./BackEnd
    container_name: assistant_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./BackEnd:/app

volumes:
  pgdata:
